version: '2.2'
services:
  react:
    container_name: redux
    image: node:alpine
    #cpuset: '1'
    #mem_limit: 512m
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
     - PORT=80
    volumes:
      - $PWD/../.npm/:/root/.npm
      - $PWD/:/root/react
    networks:
      - net
    ports:
      - '80:80'
    working_dir: /root/react
networks:
  net:
